### ISSUE TITLE
consprep crash

### ISSUE THREAD

**Issue by ntbeileh** [putnamdk/VCF2CNA-Beta#2]
When trying to run this tool, it crashed giving this error message:

My command: python3 execute.py sample_file.vcf vcffolder/ outputdirectorypath -Assembly hg38 -VcfOrder NT

Output:
Set Base Directory
Initialize input files
/VCF2CNA-Beta/vcf2cna_prep/good.bad.new.hg38
/VCF2CNA-Beta/vcf2cna_prep/hg38_winbin_100bp.txt
/VCF2CNA-Beta/vcf2cna_prep/chr_sizes_hg38.txt
Determine input filetype
VCF
Parse files based on filetype and generate snvcounts_outputfile with median_outputfile
Starting consprep
./commandline.sh: line 118: /VCF2CNA-Beta/vcf2cna_prep/consprep: cannot execute binary file
consprep crashed! aborting.

I'm not sure what to do in order to fix this. Any help would be appreciated!

**Comment by putnamdk** [comment]
The tool was developed using python 2.7.12.  I noticed you are invoking the call with python3.
This has the potential to introduce errors in the pipeline.

consprep is a binary file compiled for linux x86-64
Are you running on a different system?

**Comment by ntbeileh** [comment]
My system is: Darwin 20.5.0 x86_64

I tried changing the first line to `#!/usr/bin/python2.7` of execute.py to run through that version of python using ./execute.py and I still get the same error.

**Comment by putnamdk** [comment]
The most likely error is that the compiled version of consprep and snvcounts are not compatible with your system.
I have uploaded the source code and scripts I used to compile these scripts in the newly created src folder.

Once you compile the source code, replace the consprep and snvcounts program included in vcf2cna_prep folder, with your compiled versions.

**Comment by ntbeileh** [comment]
That worked and fixed the problem thank you! I have a different unrelated problem that I will open another issue for.
