### ISSUE TITLE
Problem with vcf2cna_prep/consprep: cannot execute binary file

### ISSUE THREAD

**Issue by SergiuPasca** [putnamdk/VCF2CNA-Beta#4]
When trying to run python execute.py (either on zsh or bash) I get the following error:
./commandline.sh: line 118: /VCF2CNA-Beta/vcf2cna_prep/consprep: cannot execute binary file

When trying to run vcf2cna_prep/consprep by itself I get: zsh: exec format error
What I found was that it is possible that the way vcf2cna_prep/consprep was compiled is not compatible with my system.

Have you gotten across this in the past? If so, does anyone have any solutions?
Thank you in advance

**Comment by putnamdk** [comment]
You will need to compile consprep from source for your system
The code is found in the /VCF2CNA-Beta/src folder

The files in this folder contain the source code to create two binary programs:

 1.  consprep
 2.  snvcounts

To compile: download all files and run the build.sh script in the same directory as the files.
Move the newly created consprep and snvcounts executable files to /VCF2CNA-Beta/vcf2cna_prep folder, replacing the
non-compatible files.

**Comment by SergiuPasca** [comment]
Thank you. It worked.
